Fix the error
ReferenceError: UIAlertDialogContent is not defined
    at CombinedToolDrawer (https://6000-firebase-studio-1747154453999.cluster-hf4yr35cmnbd4vhbxvfvc6cp5q.cloudworkstations.dev/_next/static/chunks/src_components_features_43eed22a._.js:6768:230)
    at RightDockedToolbar (https://6000-firebase-studio-1747154453999.cluster-hf4yr35cmnbd4vhbxvfvc6cp5q.cloudworkstations.dev/_next/static/chunks/src_components_layout_837c80b4._.js:977:215)
    at AppLayout (https://6000-firebase-studio-1747154453999.cluster-hf4yr35cmnbd4vhbxvfvc6cp5q.cloudworkstations.dev/_next/static/chunks/src_ff8a6158._.js:624:219)
    at ClientSegmentRoot (https://6000-firebase-studio-1747154453999.cluster-hf4yr35cmnbd4vhbxvfvc6cp5q.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2108:50)

Check for OnClick conflicts